name: Executar Script Diário

on:
  schedule:
    - cron: '09 19 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Instalar Dependências
      run: |
        python -m pip install -r .github/workflows/requirements.txt

    - name: Executar o Script
      run: |
        python views.py 
